### ISSUE TITLE
rexp_prepare_deconseq.py fails to produce output files

### ISSUE THREAD

**Issue by abshah** [fjruizruano/satminer#1]
Hi, 

I want to run rexp_prepare_deconseq.py. I also found that seqtk fails if there is space or blank character in the sequence names. Furthermore, seqtk seq has changed flags (from -a to -A) for forcing FASTA output. 

My command is :

`>rexp_prepare_deconseq.py 100000 All_reads_R1_001.fastq All_reads_R2_001.fastq test1
`

And my console output looks like this:

```
Usage: rexp_prepare.py NumberOfPairedReads File_1.fastq File_2.fastq [PREFIX]

Analyzing All_reads_R1_0

Running Fastq-combine-pe
fastq_paired_combine_id.py All_reads_R1_001.fastq All_reads_R2_001.fastq
Usage: fastq_paired_combine_id.py file_1.fastq file_2.fastq
Getting read names
Getting common reads
Extracting reads from original files
We're done!
Running Fastq-pe-random
seqtk sample -s 100 All_reads_R1_0_paired_1.fastq 100000 > All_reads_R1_0_paired_1.fastq.subset
seqtk sample -s 100 All_reads_R1_0_paired_2.fastq 100000 > All_reads_R1_0_paired_2.fastq.subset

Running Shuffling
shuffleSequences_fastq.pl 
All_reads_R1_0_paired_1.fastq.subset 
All_reads_R1_0_paired_2.fastq.subset 
All_reads_R1_0_all_test1100000.fastq

Editing All_reads_R1_0_all_test1100000.fastq

Running Fastq to fasta
seqtk seq -a All_reads_R1_0_all_test1100000.fastq > All_reads_R1_0_all_test1100000.fasta

We're done!
```

The contents of my working directory looks like this:

```

-rw-r--r--  1 ashah animalbehaviour 2.0G Aug 23 12:30 All_reads_R1_001.fastq
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:34 All_reads_R1_0_all_test1100000.fasta
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:34 All_reads_R1_0_all_test1100000.fastq
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:33 All_reads_R1_0_paired_1.fastq
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:34 All_reads_R1_0_paired_1.fastq.subset
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:33 All_reads_R1_0_paired_2.fastq
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:34 All_reads_R1_0_paired_2.fastq.subset
-rw-r--r--  1 ashah animalbehaviour 2.0G Aug 23 13:30 All_reads_R2_001.fastq

```

Best Wishes,
Abhijeet

**Comment by abshah** [comment]
Sorry, I overlooked some thing simple!

**Comment by fjruizruano** [comment]
@abshah I just saw your issue. Please, let me know if you need some help.
Bests.

**Comment by abshah** [comment]
@fjruizruano , please have a look at the open issues.

**Comment by aline-pfelix** [comment]
> Sorry, I overlooked some thing simple!

Hi!!
What did you forget?
I seem to have the same problem

**Comment by fjruizruano** [comment]
Hi @aline-pfelix,

Thanks for you comment. Could you be more specific, please?

Best.

**Comment by aline-pfelix** [comment]
@fjruizruano 

i'm having the exact same problem he showed. The script runs correctly, but it creates 6 blank output files.

like this
-rw-r--r--  1 ashah animalbehaviour 2.0G Aug 23 12:30 All_reads_R1_001.fastq
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:34 All_reads_R1_0_all_test1100000.fasta
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:34 All_reads_R1_0_all_test1100000.fastq
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:33 All_reads_R1_0_paired_1.fastq
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:34 All_reads_R1_0_paired_1.fastq.subset
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:33 All_reads_R1_0_paired_2.fastq
-rw-r--r--  1 ashah animalbehaviour    0 Aug 23 13:34 All_reads_R1_0_paired_2.fastq.subset
-rw-r--r--  1 ashah animalbehaviour 2.0G Aug 23 13:30 All_reads_R2_001.fastq

**Comment by fjruizruano** [comment]
Thanks @aline-pfelix!

Which is the format of the read IDs in your FASTQ files? It should be:

lib_1.fastq:
```
@read:id:number/1
```

lib_2.fastq:
```
@read:id:number/2
```

If not, you can use the script  "fastq_edit_ids.py". For it, your fastq file names need to be in the format lib_1.fastq/lib_2.fastq.

I hope this helps. Please let me know if you need more details.
Cheers.

**Comment by aline-pfelix** [comment]
@fjruizruano

Thank you for your help!!
Trouble is solved.

Best,

**Comment by fjruizruano** [comment]
Great to hear it!
Best.
