### ISSUE TITLE
about running satminer

### ISSUE THREAD

**Issue by abshah** [fjruizruano/satminer#2]
Hi @fjruizruano,

I have a few questions regarding running satminer (as in the example in the documentation). 

1. Is rexp_select_contigs.py the same as rexp_get_contigs.py ?
2. While running rm_homology.py, i get the error:

`[ashah@wayne clusters]$ rm_homology.py out.txt
Usage: rm_homology.py FastaFile
RepeatMasker version open-4.0.6
Search Engine: Crossmatch [ 0.990329 ]
Master RepeatMasker Database: 
/repeatexplorer/RepeatMasker/Libraries/RepeatMaskerLib.embl ( Complete Database: 20160829 )
Custom Repeat Library: tmp_db.fas

analyzing file tmp_query.fas
FastaDB::compact - Error could not locate file /satminer_Gsib_RE_run1/seqClust/clustering/clusters/RM_54614.MonFeb61512012017/tmp_query.fas!
 at /repeatexplorer/RepeatMasker/RepeatMasker line 751.
Traceback (most recent call last):
  File "/homes/ashah/bin/rm_homology.py", line 45, in <module>
    tmp_out = open("tmp_query.fas.out").readlines()
IOError: [Errno 2] No such file or directory: 'tmp_query.fas.out'`

I suspect it is not copying/moving the "tmp_query.fas" to the temporary directory. 

Best Wishes,
Abhijeet

**Comment by fjruizruano** [comment]
Hi @abshah 

About question 1. There was an error in the README file. Instead of "rexp_select_contigs.py" it should said "rexp_get_contigs.py". I have already solve this error.

About question 2. The script rm_homology.py is used to an all-to-all comparison of all extracted satDNA sequences got in the previous steps with RepeatMasker. It is not tought to use with the output of the script "rexp_get_contigs.py". In addition, you need the sequence id in the RepeatMasker format, for example: >sequences#Satellite/Sat01.

Bests,
Francisco.

**Comment by abshah** [comment]
Hi @fjruizruano ,

Perhaps, I should explain exactly what I did and what output I got, when I tried running satminer.

#1. prepare sequences for RepeatExplorer
rexp_prepare.py 100000 All_reads_R1_001.fastq All_reads_R2_001.fastq 
###output: All_reads_R1_001_paired.fasta.subset All_reads_R2_001_paired.fasta.subset ###

#2. Run RepeatExplorer with default options 
./run_RE_for_satminer.sh 
###output seqClust/ summary/ folders ###

#3. Run rexp_get_contigs script in seqClust/clustering/clusters folder
cd seqClust/clustering/clusters
rexp_get_contigs.py 
###output files out.list out.txt ###

#4. Extract sequences as a FASTA file
extract_seq.py out.txt out.list 
###output: out.list.extract FASTA file ###

#5. Run DeconSeq
##deconseq_run.py ListOfFastaFiles Reference Threads##

## Here I dont know which file contains the ListOfFasta files as I end up with 3 files: out.list out.txt out.list.extract ##

##out.list contains : ##
head out.list
CL1Contig1
CL2Contig1
CL3Contig4
CL4Contig1
CL4Contig8
CL5Contig1
CL6Contig24
CL6Contig3
CL6Contig28
CL6Contig21

##out.txt contains##
head out.txt
>CL1Contig1 (2222-220.0-488891)
CCTCTACGGCACTAGTATCTGTCGTTTTCGAAGTCTAAAATGACAATAAGAAACCACTTA
TTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATGAAGGATAGCTGCAGGTGC
AGTGTGCAGTCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGATAGAGCCGT
TTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTA
ACTTCGAAAACGACGGATACTAGTGCCATCAAGGATAGCTGCAGGTGCAGTGTGCAGCCT
GGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTAT
ATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACG
ACGGATACTAGTGCCATAGAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAA
ATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTT

##out.list.extract contains##
>CL1Contig1
CCTCTACGGCACTAGTATCTGTCGTTTTCGAAGTCTAAAATGACAATAAGAAACCACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATGAAGGATAGCTGCAGGTGCAGTGTGCAGTCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGATAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATCAAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATAGAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACTACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATCAAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATCAAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATCAAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGAAAATGTTATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATCAAGGATAGCTGCAGGTGCAGTGTGCAGCCAGATAAATGTAAAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATCAAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATCAAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATAGAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATAAAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTGAATGGAAACGACTTATTGTCATTTCTATTTTCGAAAACGACGGATACTAGTGCCATAGAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATTGTGTATATTTCGTGTTTTGTGCATTTCCATGGAAACGACTTATTGTCATTTCTAACTTCGAAAACGACGGATACTAGTGCCATCAAGGATAGCTGCAGGTGCAGTGTGCAGCCTGGTAAATGTAAAATGTTAAATTACATTGTCTAAGAGGGCTAGAGCCGTTTAATGGTGTATAT
...........{2-line FASTA file}


Best Wishes,
Abhijeet

**Comment by fjruizruano** [comment]
Hi @abshah,

Thank you for the explanation.

Firstly, do you need to have the Deconseq's directory in the location /usr/local/lib. Otherwise, you can modify the script with the alternative location.

Additionally, you need a text file with the name of the two FASTQ (not FASTA) to be filtered with Deconseq. For example, you can use the "ls" command:

$ ls file_1.fastq file_1.fastq > list.txt

The "list.txt" file will have this structure:

file_1.fastq
file_2.fastq

As "Reference" you should use the "out.list.extract" FASTA file. And as "Threads" you should indicate the number of threads you want to use. For large FASTQ files, i. e., larger than 10 Gb, I recommend to use several threads to reduce the computation time. I use 12 threads.

I expect it is more clear for you.
Bests,
Francisco.

**Comment by abshah** [comment]
Hi @fjruizruano,

Thank You for your prompt reply!

I did exactly as you suggested, and but now I have another issue!
 

 /seqClust/clustering/clusters> deconseq_run.py fastq_file_list.txt out.list.extract 4
Usage: deconseq_run.py ListOfFiles Reference Threads
[bwa_index] Pack FASTA... 0.01 sec
[bwa_index] Reverse the packed sequence... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.04 seconds elapse.
[bwa_index] Construct BWT for the reverse packed sequence...
[bwa_index] 0.04 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Update reverse BWT... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.02 sec
[bwa_index] Construct SA from reverse BWT and Occ... 0.01 sec
Sequences: 99999
Files: 4
Sequences: 99999
Files: 4
Running DeconSeq
Bareword "out" not allowed while "strict subs" in use at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 19.
BEGIN not safe after errors--compilation aborted at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 25.
Compilation failed in require at deconseq.pl line 26.
BEGIN failed--compilation aborted at deconseq.pl line 26.
Bareword "out" not allowed while "strict subs" in use at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 19.
BEGIN not safe after errors--compilation aborted at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 25.
Compilation failed in require at deconseq.pl line 26.
BEGIN failed--compilation aborted at deconseq.pl line 26.
Bareword "out" not allowed while "strict subs" in use at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 19.
BEGIN not safe after errors--compilation aborted at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 25.
Compilation failed in require at deconseq.pl line 26.
BEGIN failed--compilation aborted at deconseq.pl line 26.
Bareword "out" not allowed while "strict subs" in use at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 19.
BEGIN not safe after errors--compilation aborted at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 25.
Compilation failed in require at deconseq.pl line 26.
BEGIN failed--compilation aborted at deconseq.pl line 26.
Bareword "out" not allowed while "strict subs" in use at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 19.
BEGIN not safe after errors--compilation aborted at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 25.
Compilation failed in require at deconseq.pl line 26.
BEGIN failed--compilation aborted at deconseq.pl line 26.
Bareword "out" not allowed while "strict subs" in use at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 19.
BEGIN not safe after errors--compilation aborted at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 25.
Compilation failed in require at deconseq.pl line 26.
BEGIN failed--compilation aborted at deconseq.pl line 26.
Bareword "out" not allowed while "strict subs" in use at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 19.
BEGIN not safe after errors--compilation aborted at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 25.
Compilation failed in require at deconseq.pl line 26.
BEGIN failed--compilation aborted at deconseq.pl line 26.
Bareword "out" not allowed while "strict subs" in use at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 19.
BEGIN not safe after errors--compilation aborted at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/deconseq-standalone-0.4.3/All_reads_R1_001_paired/DeconSeqConfig.pm line 25.
Compilation failed in require at deconseq.pl line 26.
BEGIN failed--compilation aborted at deconseq.pl line 26.
cat: 'tmp_queries_1.1.fastq.dir/*clean*': No such file or directory
cat: 'tmp_queries_1.2.fastq.dir/*clean*': No such file or directory
cat: 'tmp_queries_1.3.fastq.dir/*clean*': No such file or directory
cat: 'tmp_queries_1.4.fastq.dir/*clean*': No such file or directory
cat: 'tmp_queries_2.1.fastq.dir/*clean*': No such file or directory
cat: 'tmp_queries_2.2.fastq.dir/*clean*': No such file or directory
cat: 'tmp_queries_2.3.fastq.dir/*clean*': No such file or directory
cat: 'tmp_queries_2.4.fastq.dir/*clean*': No such file or directory
rm: cannot remove 'tmp_queries*.fastq.dir': No such file or directory

**Comment by fjruizruano** [comment]
Hi @abshah,

It looks as a deconseq issue. Do you have execution permission for the files "bwa64", "bwaMAC", "deconseq.pl" and "splitFasta.pl"?

Bests,
Francisco.

**Comment by abshah** [comment]
Hi @fjruizruano ,

It seems to be executable. Here are the contents of my deconseq directory.

~/deconseq-standalone-0.4.3> ls -lh
total 571K
-rwxr-xr-x+ 1 ashah users 618K May  5  2013 bwa64
-rwxr-xr-x+ 1 ashah users 240K May  5  2013 bwaMAC
drwxr-xr-x+ 2 ashah users    9 May  5  2013 bwasw_modified_source
-rw-r--r--+ 1 ashah users 2.3K May  5  2013 ChangeLog
-rw-r--r--+ 1 ashah users  35K May  5  2013 COPYING
-rw-r--r--+ 1 ashah users 1.6K May  5  2013 DeconSeqConfig.pm
-rwxr-xr-x+ 1 ashah users  21K May  5  2013 deconseq.pl
-rwxr-xr-x+ 1 ashah users  13K Aug 31 17:01 fasta-splitter.pl
-rw-r--r--+ 1 ashah users 5.7K May  5  2013 README
-rwxr-xr-x+ 1 ashah users 8.0K May  5  2013 splitFasta.p

Perhaps, is it python, perl, or linux issue?

I am using Perl:

perl -v
This is perl 5, version 24, subversion 0 (v5.24.0) built for x86_64-linux-thread-multi
(with 50 registered patches, see perl -V for more detail)

I am using python:

python --version
Python 2.7.12 :: Anaconda custom (64-bit)

Linux:

uname -a
Linux statler 4.8.14-300.fc25.x86_64 #1 SMP Mon Dec 12 16:31:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fjruizruano** [comment]
Hi @abshah,

To test if is a dependencies problem, you can try to run deconseq manually. In this link you have my own protocol:

https://littlebioinformatician.wordpress.com/scripts/deconseq/

Bests,
Francisco.

**Comment by abshah** [comment]
Hi @fjruizruano ,

Thank You for pointing me to the manual deconseq protocol. It helped me figure out exactly which step had an issue. 

I suspected the error is occurring when the deconseq temporary configuration file is created (see lines 43:48 in deconseq_run.py). In my naive understanding of programming, I feel it may have been caused by the '.' character in the dbs flag.
```

>perl deconseq.pl -f All_reads_R1_001_paired.fastq.subset -out_dir temp1 -dbs out.list.extract -keep_tmp_files

 Bareword "out" not allowed while "strict subs" in use at  /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/DeconSeqConfig.pm line 19.
 Bareword "txt" not allowed while "strict subs" in use at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/DeconSeqConfig.pm line 19.
 BEGIN not safe after errors--compilation aborted at /vol/animalbehaviour/sat_miner_Gsib_test/satminer_Gsib_RE_run1/seqClust/clustering/clusters/DeconSeqConfig.pm line 26.
 Compilation failed in require at deconseq.pl line 26.
 BEGIN failed--compilation aborted at deconseq.pl line 26.

>perl deconseq.pl -f All_reads_R1_001_paired.fastq.subset -out_dir temp1 -dbs out -keep_tmp_files
[bsw2_aln] read 41394 sequences (10000043 bp)...
[bsw2_aln] read 41316 sequences (10000206 bp)...
[bsw2_aln] read 17290 sequences (4175590 bp)...
>cd temp1
> ls -lh
total 66M
-rw-r--r-- 1 ashah animalbehaviour    0 Feb  8 12:16 1486552617
-rw-r--r-- 1 ashah animalbehaviour  37M Feb  8 12:19 1486552617_clean.fq
-rw-r--r-- 1 ashah animalbehaviour  16M Feb  8 12:19 1486552617_cont.fq
-rw-r--r-- 1 ashah animalbehaviour 2.4M Feb  8 12:19 1486552617_out_out.list.extract.tsv




```

Thank You!
Abhijeet

**Comment by fjruizruano** [comment]
Hi @abshah,

I think you are right.

Can you rename the file "out.list.extract" as "something.fasta" or "something.fas"?

Bests,
Francisco.

**Comment by abshah** [comment]
Hi @fjruizruano ,

Thank You for helping out.

In the next steps, when I run the **rm_homology.py** to generate homology among consensus sequences, with the command

`rm_homology.py 1486552617_cont.fasta`

I end up a file called output which contains the following:
```
MISEQ:28:000000000-A9R37:1:1113:10880:11825:
--MISEQ:28:000000000-A9R37:1:1106:12140:12257#Unspecified
--MISEQ:28:000000000-A9R37:1:1106:12140:12257#Unspecified
--MISEQ:28:000000000-A9R37:1:1106:12140:12257#Unspecified
--MISEQ:28:000000000-A9R37:1:1106:12140:12257#Unspecified
--MISEQ:28:000000000-A9R37:1:1106:12140:12257#Unspecified
--MISEQ:28:000000000-A9R37:1:1106:12140:12257#Unspecified
--MISEQ:28:000000000-A9R37:1:1106:12140:12257#Unspecified
--MISEQ:28:000000000-A9R37:1:1106:12140:12257#Unspecified
--MISEQ:28:000000000-A9R37:1:1106:12140:12257#Unspecified
```

and my console output looks like this:

```
RepeatMasker version open-4.0.6
Search Engine: Crossmatch [ 0.990329 ]
Master RepeatMasker Database: /vol/animalbehaviour/repeatexplorer/RepeatMasker/Libraries/RepeatMaskerLib.embl ( Complete Database: 20160829 )
Custom Repeat Library: tmp_db.fas



analyzing file tmp_query.fas
identifying matches to tmp_db.fas sequences in batch 1 of 1
processing output:
cycle 1
cycle 2
Generating output...
masking
done
```

I suspect it is a looping issue with running RepeatMasker with 1 sequence at a time.  

Thank You

Best Wishes,
Abhijeet

**Comment by fjruizruano** [comment]
Hi @abshah,

The script "rm_homology.py" is thought to analyse the consensus sequence generated in the first part of the protocol. If you look at the image for the satMiner protocol, you will see that.

You should run DeconSeq for the *_1.fastq file with the whole library and a different DeconSeq run for the *_2.fastq. DeconSeq generates a *_clean.fq for each run. And then you should use the "rexp_prepare_deconseq.py" script to continue with the protocol. This last step wasn't in the README file. I just added it.

Bests,
Francisco.
