### ISSUE TITLE
Trouble installing satminer

### ISSUE THREAD

**Issue by RxLoutre** [fjruizruano/satminer#3]
Hello !

I would like to use satminer to characterize satellite element within several drosophila genomes.

I have some trouble understanding how exactly to install satminer.

The only indication in the installation section is "Copy script to your binary folder", which doesn't make that much sense to me. Can I have further explanations ? When you say "script" it talk about the dependencies or the satminer scripts ?

I already downloaded all the dependencies, and put the binaries inside satminer folder. But when I tried to run the following command : 
`
python rexp_prepare_deconseq.py 100000 '/media/loutre/SUZUKII/illumina_reads/SRR942797_1.fastq' '/media/loutre/SUZUKII/illumina_reads/SRR942797_2.fastq'`

I got this error : 
```
Usage: rexp_prepare.py NumberOfPairedReads File_1.fastq File_2.fastq [PREFIX]

Analyzing /media/loutre/SUZUKII/illumina_reads/SRR942797

Running Fastq-combine-pe
fastq_paired_combine_id.py /media/loutre/SUZUKII/illumina_reads/SRR942797_1.fastq /media/loutre/SUZUKII/illumina_reads/SRR942797_2.fastq
/bin/sh: 1: fastq_paired_combine_id.py: not found
Running Fastq-pe-random
seqtk sample -s 100 /media/loutre/SUZUKII/illumina_reads/SRR942797_paired_1.fastq 100000 > /media/loutre/SUZUKII/illumina_reads/SRR942797_paired_1.fastq.subset
/bin/sh: 1: seqtk: not found
seqtk sample -s 100 /media/loutre/SUZUKII/illumina_reads/SRR942797_paired_2.fastq 100000 > /media/loutre/SUZUKII/illumina_reads/SRR942797_paired_2.fastq.subset
/bin/sh: 1: seqtk: not found

Running Shuffling
shuffleSequences_fastq.pl /media/loutre/SUZUKII/illumina_reads/SRR942797_paired_1.fastq.subset /media/loutre/SUZUKII/illumina_reads/SRR942797_paired_2.fastq.subset /media/loutre/SUZUKII/illumina_reads/SRR942797_all_100000.fastq

/bin/sh: 1: shuffleSequences_fastq.pl: not found
Editing /media/loutre/SUZUKII/illumina_reads/SRR942797_all_100000.fastq

Traceback (most recent call last):
  File "rexp_prepare_deconseq.py", line 86, in <module>
    fastq = open(name+"_all_"+prefix+str(sel_reads)+".fastq").readlines()
IOError: [Errno 2] No such file or directory: '/media/loutre/SUZUKII/illumina_reads/SRR942797_all_100000.fastq'
```

About the last error, the file SRR942797_all_100000.fastq was existing at the right adress. I don't understand this error and I suppose that this is a installation problem.

Do you think you can help me a bit with this ?

Thanks a lot,

Roxane

**Comment by RxLoutre** [comment]
Woups, look like I wasn't smart on this... Just added the binaries of seqtk and dependencies in my $PATH, it solved the issue and satminer is now running.

Sorry !

**Comment by RxLoutre** [comment]
Well, I got a new error about a file who is missing : 

shuffleSequences_fastq.pl

Where should I find this one ?

Thanks !

**Comment by RxLoutre** [comment]
I've downloaded the missing file from velvet, so now satminer is not showing any errors messages, but the output files are empty.

**Comment by fjruizruano** [comment]
Hi @RxLoutre,

I wil write you to your institutional email.

Bests,
Francisco.

**Comment by fjruizruano** [comment]
Hi @RxLoutre,
Yes, it is a script from the Velvet suite. I have already added this script to the repository.
Bests.

**Comment by fjruizruano** [comment]
Hi @RxLoutre,
What is the format of the your FASTQ IDs? Can you show the first line of a FASTQ file?
Bests.
