### ISSUE TITLE
about running satminer with single-end read data

### ISSUE THREAD

**Issue by abshah** [fjruizruano/satminer#4]
Hi @fjruizruano ,

I was wondering how we could modify the protocol to use satminer with single-end read data? Is there a specific provision to do so? Or we should try to what would make sense ?

Best Wishes,
Abhijeet

**Comment by fjruizruano** [comment]
Hi @abshah!

The protocol is though to paired-end data. But I can help you to use satMiner with single-end data.
Which platform have you used for the sequencing?

Bests,
Francisco.

**Comment by abshah** [comment]
Hi @fjruizruano ,

I am using the Illumina HiSeq platform with single-end reads of 150 bp. 

Best Wishes,
Abhijeet

**Comment by fjruizruano** [comment]
Hi @abshah,
Ok. I will modify some scripts to run satMiner with single-end reads this weekend. I will let you know when they are ready.
Bests,
Francisco.

**Comment by fjruizruano** [comment]
Hi @abshah,
I have adapted the the satMiner protocol to single-end libraries. I create two new scripts:

1) SE_rexp_prepare.py replaces to both, rexp_prepare.py and rexp_prepare_deconseq.
2) SE_deconseq_run.py replaces to deconseq_run.py.

Let me know your experience with this new scripts.
Bests,
Francisco.

**Comment by abshah** [comment]
Hi @fjruizruano ,

The SE scripts almost work perfectly. I have come across a few minor issues.

1. SE_deconseq_run.py: when I run SE_deconseq_run.py as 
`
SE_deconseq_run.py fastq_SE_reads.1.fastq cluster_extract.fasta 4
`
I get:
```
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Update reverse BWT... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.01 sec
[bwa_index] Construct SA from reverse BWT and Occ... 0.01 sec
Sequences: 12508407
Files: 4
-p destination: Broken pipe
-p destination: Broken pipe
-p destination: Broken pipe
-p destination: Broken pipe
[bsw2_aln] read 66845 sequences (10000020 bp)...
[bsw2_aln] read 66847 sequences (10000125 bp)...
[bsw2_aln] read 66844 sequences (10000111 bp)...
[bsw2_aln] read 66844 sequences (10000031 bp)...
[bsw2_aln] read 66844 sequences (10000007 bp)...
[bsw2_aln] read 66846 sequences (10000109 bp)...
```
Other than that, it seems to work fine. 

2. SE_rexp_prepare.py:
line 54:
`
trimmomatic = "trimmomatic SE -phred33 %s %s ILLUMINACLIP:/usr/local/lib/Trimmomatic-0.32/adapters/TruSeq3-PE.fa:2:30:10 LEADIN        G:3 TRAILING:3 SLIDINGWINDOW:4:%s MINLEN:%s" % (r1, rr1+"_paired.fastq", mq, ml)
`
I am not sure if the TruSeq3-PE and TruSeq3-SE have all the same adapters. 
Additionally, the "_paired.fastq" file ending could be potentially confusing for some users.

**Thank You** very much for writing these scripts !

Best Wishes,
Abhijeet

**Comment by fjruizruano** [comment]
Dear @abshah,
About question 1. I always get the "-p destination: Broken pipe" message, but DeconSeq looks to run well.
About question 2. Thank you for advise about this two issues in the SE_rexp_prepare.py. I updated the script to replace "paired" by "trimmed" and use the adpaters for TruSeq3-SE.

Bests,
Francisco.
