### ISSUE TITLE
about using the same seed for multiple runs with seqtk

### ISSUE THREAD

**Issue by abshah** [fjruizruano/satminer#6]
Hi @fjruizruano ,

I have just noticed that satminer uses the same seed number with seqtk sample (seed number: 100) everytime it is run. Do you think it may have an effect on the final results ?

Best Wishes,
Abhijeet

**Comment by fjruizruano** [comment]
Hi @abshah,

Since you filter out repetitive sequences in a round and then you continue with the "clean" reads fo the next round, the seed do not biases the results.

Bests,
Francisco.
