### ISSUE TITLE
about rm_homology.py

### ISSUE THREAD

**Issue by mlauragonzalez23** [fjruizruano/satminer#8]
Hi!
I have this issue: I already have a fasta file of consensus satDNAs sequences previously isolated with another methods. I would like to use the rm_homology.py script and calcule the divergence, so I tried start with satminer from "2. satDNA analysis". When i tried to run rm_homology.py, I see the next error:

Usage: rm_homology.py FastaFile
/bin/sh: 1: RepeatMasker: not found
Traceback (most recent call last):
  File "/usr/local/bin/rm_homology.py", line 45, in <module>
    tmp_out = open("tmp_query.fas.out").readlines()
IOError: [Errno 2] No such file or directory: 'tmp_query.fas.out'

is it neccesary to use a specific fasta file obteined from previous satminer steps? Or am I having a trouble with RepeatMasker?
Thanks!

**Comment by fjruizruano** [comment]
Hi Laura!

First at all, you need to install RepeatMasker. Additionally, I recommend to have a FASTA file with the IDs in RepeatMasker format:

>sat1#Satellite/sat1

I hope it helps,
Cheers.

**Comment by mlauragonzalez23** [comment]
Thanks! So, probably my trouble is the RM installation. I' ll try to fix that and use the IDs as you say.
